Create and view
QuanXuuu/Capstone-project pull request #9
Opened 2022-07-07 08:28 UTC by QuanXuuu

2022-07-07 10:41 UTC, stefankorder approved these changes
Good work!

2022-07-08 13:24 UTC, AnnaGrasm commented on src/App.js
> +import {Routes, Route, Outlet} from 'react-router-dom';
Outlet is new for me ;)

2022-07-08 13:34 UTC, QuanXuuu commented on src/App.js
> +import {Routes, Route, Outlet} from 'react-router-dom';
I used it for nested routes :)

2022-07-08 13:51 UTC, macfrei requested changes
Hi Quan, I added some comments. Please consider my comments about your state management solution with local storage. 😬

2022-07-08 13:51 UTC, macfrei commented on src/App.js
> +  setToLocal('recipes', recipes);
Hi Quan, I would highly recommend to not use `localStorage` as a state context between your components. The way you did it before, with a global state within your `App.js` is considered a better practice. 

I would strongly advise you to change your code back and not use `localStorage` like this. 😬 And to first do it how we approached state and global state. 

Is there a specific reason why you do it like this?

2022-07-08 13:51 UTC, macfrei commented on src/components/RecipeForm/RecipeForm.js
> +    console.log(recipe);
Please remove the `console.log`s before merging.
```suggestion
```

2022-07-08 13:51 UTC, macfrei commented on src/components/RecipeForm/RecipeForm.js
> +      <br></br>
Please use CSS to add break lines and no extra HTML elements :)
```suggestion
      <IngredientsForm onAddIngredients={addIngredients} />
```

2022-07-08 13:51 UTC, macfrei commented on src/pages/RecipeDetail.js
> +  let params = useParams();
```suggestion
  const params = useParams();
```

2022-07-08 16:21 UTC, QuanXuuu commented on src/App.js
> +  setToLocal('recipes', recipes);
Hi Lene, 
I thought instead of using `backend database` , I could use `localstorage` to save the info. Then the use has his/her own record, and no need to add the same info every time he/she open this App. In short, I used `localstorage` as a simplified small `backend DB`.

I assume people don't use `localstorage` in this way, but could you please kindly explain the reason ? Many thanks in advance !

Of course, I will change my code back and use `global state` instead :)

2022-07-09 21:42 UTC, QuanXuuu commented on src/App.js
> +  setToLocal('recipes', recipes);
Make sense now:) The code is much more cleaner and shorter :)

2022-07-11 06:25 UTC, macfrei commented on src/App.js
> +  setToLocal('recipes', recipes);
Hi Quan :) sorry for the late reply. Your reasoning to use `localStorage` is totally valid. It is just rather uncommon to use it as you have been. It might lead to issues somewhere down the road. You can still use `localStorage` though :)

2022-07-11 06:32 UTC, macfrei reviewed
Nice job! 🥳 🙌 👍

2022-07-11 06:32 UTC, macfrei commented on src/components/RecipeForm/RecipeForm.js
>            <IngredientItem key={id}>{ingredient}</IngredientItem>
This `id` is not an `id` but the `index`. I would recommend to name it `index` :)
```suggestion
        {ingredients.map((ingredient, index) => (
          <IngredientItem key={index}>{ingredient}</IngredientItem>
```

2022-07-11 06:32 UTC, macfrei commented on src/pages/Home.js
> +  console.log(recipes);
```suggestion
```

2022-07-11 06:32 UTC, macfrei commented on src/pages/RecipeCreate.js
> +      <RecipeForm addRecipe={addRecipe} />
Usually when passing a callback function as props, we start with the prefix `on` to clarify that this is a callback function. In this case it would be `onAddRecipe` and then the function itself in your `App.js` would be `addRecipe`. The same with `addIngredient`. That one would be `onAddIngredient` like you had before :)

2022-07-11 06:32 UTC, macfrei commented on src/pages/RecipeDetail.js
> +  const recipe = recipes.filter(recipe => recipe.id === params.id)[0];
I would recommend to use `find` instead of `filter` here. Then you don't need the square bracket syntax to get the first element. `find` already returns the object.
```suggestion
  const recipe = recipes.find(recipe => recipe.id === params.id);
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2022-07-11 08:45 UTC, macfrei approved these changes
Well done!

2022-07-11 10:14 UTC, macfrei approved these changes
👍

2022-07-11 10:54 UTC, merged